# Basic site settings
locale                   : "en-GB"
site_theme               : "default"
title                    : "Samuel Osian"
title_separator          : "-"
name                     : &name "Samuel Osian"
description              : &description "I'm Sam, a dedicated professional in Health Data Science and AI. On this blog, I share insights and personal reflections that bridge cutting-edge research with everyday application."
url                      : "https://sam-osian.github.io" 
baseurl                  : "" 
repository               : "Sam-Osian/sam-osian.github.io"


github_username: "Sam-Osian"

# Sitemap & Feeds (Useful for search engines)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Blog Settings
paginate: 5  # Number of posts per page
paginate_path: "/blog/page:num/"
future: false  # Avoids publishing future-dated posts
timezone: "Europe/London"
collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/
kramdown: # Table of contents
  toc_levels: 1..3
  input: GFM
  syntax_highlighter: rouge


# Site Author Information
author:
  avatar           : "profile.png"
  name             : "Samuel Osian"
  bio              : "Health Data Science & AI"
  location         : "Liverpool, United Kingdom"
  email            : "soandrews98@gmail.com"  
  github           : "Sam-Osian"
  linkedin         : "https://www.linkedin.com/in/sam-o-andrews/"


# Academic Profiles
author_profiles:
  #googlescholar    : ""
  orcid            : "https://orcid.org/0009-0000-7644-6218"
  #researchgate     : ""
  #pubmed           : ""

# Social Media
social:
  links:
    - "https://github.com/Sam-Osian"
    - "https://www.linkedin.com/in/sam-o-andrews/"

# SEO Settings
favicon: "/favicon.ico"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji

# Permalinks
permalink: /:categories/:title/

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Thoughts"
    url: "/thoughts/"
  - title: "Projects"
    url: "/projects/"

# Custom 404 Page
permalink: /404.html

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Kramdown Configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Comments 
comments:
  provider: false  # Change to "disqus" or "custom" if needed

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Output Settings
incremental: false  # Disable incremental build (can cause issues)
read_more: "disabled"  # No "Read More" links
breadcrumbs: false  # No breadcrumbs
words_per_minute: 160

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Conversion
lsi: false
excerpt_separator: "\n\n"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed  # Compress CSS output

# Mimic GitHub Pages Safe Mode
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji